/**
 * Reads environment variables (from a .env file or OS env) and writes
 * src/environments/environment.ts and environment.prod.ts before build/serve.
 *
 * Usage:
 *   node scripts/set-env.js               # reads .env + OS env
 *   API_BASE_URL=https://... node scripts/set-env.js   # OS env only
 */

const fs = require('fs');
const path = require('path');

// Load .env if it exists — OS env vars take precedence (never override)
const dotenvPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(dotenvPath)) {
  const lines = fs.readFileSync(dotenvPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    if (key && process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

const apiBaseUrl = process.env['API_BASE_URL'];
if (!apiBaseUrl) {
  console.error('\nset-env ERROR: API_BASE_URL is not set.');
  console.error('Create frontend/.env from frontend/.env.example, or export the variable directly.\n');
  process.exit(1);
}

const envDir = path.join(__dirname, '..', 'src', 'environments');

const devContent = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
// To change values, update .env (dev) or set the environment variable in CI.
export const environment = {
  production: false,
  apiBaseUrl: '${apiBaseUrl}'
};
`;

const prodContent = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiBaseUrl: '${process.env['API_BASE_URL_PROD'] || apiBaseUrl}'
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), devContent);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), prodContent);

console.log(`set-env: apiBaseUrl      = ${apiBaseUrl}`);
if (process.env['API_BASE_URL_PROD']) {
  console.log(`set-env: apiBaseUrl(prod) = ${process.env['API_BASE_URL_PROD']}`);
}
