// AUTO-GENERATED by scripts/set-env.js — do not edit manually.
// To change values, update .env (dev) or set the environment variable in CI.
export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:8080/internship-portal/api/v1'
};
